name = "discord-code-review-bot-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-04-26"

[placement]
mode = "smart"


[[kv_namespaces]]
binding = "discord_code_review_bot_throttles"
id = ""

[ai]
binding = "ai"
